#!/bin/bash
cat <<EOF > $HOME/install_packages.yml
---
- name: Install required packages and software on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - build-essential
          - libpq-dev
          - python3-dev
          - curl
          - wget
          - rsync
          - software-properties-common
          - postgresql
          - postgresql-contrib
        state: present

    - name: Check if Node.js is installed
      command: node -v
      register: node_version
      ignore_errors: yes

    - name: Install Node.js if not present
      block:
        - name: Download Node.js setup script
          ansible.builtin.get_url:
            url: https://deb.nodesource.com/setup_20.x
            dest: /tmp/setup_node.sh
            mode: '0755'
        - name: Execute Node.js setup script
          ansible.builtin.shell: bash /tmp/setup_node.sh
        - name: Install Node.js
          ansible.builtin.apt:
            name: nodejs
            state: latest

    - name: Check if n8n is installed
      command: n8n --version
      register: n8n_version_result
      ignore_errors: true

    - name: Install n8n if not already installed
      block:
        - name: Install n8n globally using npm
          ansible.builtin.shell: sudo npm install n8n -g
      when: n8n_version_result.rc != 0

    - name: Check if ClusterControl is installed
      command: cmon --version
      register: cmon_version_result
      ignore_errors: true

        - name: Download and install ClusterControl if not present
          ansible.builtin.shell: |
            curl -L https://severalnines.com/downloads/cmon/install-cc -o install-cc
            chmod +x install-cc
            ./install-cc
          when: cmon_version_result.rc != 0
EOF